export const RESTAURANT_LIST_LOADING = "RESTURANT_LIST_LOADING";
export const RESTAURANT_LIST_SUCCESS = "RESTAURANT_LIST_SUCCESS";
export const RESTAURANT_LIST_FAILURE = "RESTAURANT_LIST_FAILURE";

export const SEARCH = "SEARCH";

export const RESTAURANT_SELECT_LOADING = "RESTURANT_LIST_LOADING";
export const RESTAURANT_SELECT_SUCCESS = "RESTAURANT_LIST_SUCCESS";
export const RESTAURANT_SELECT_FAILURE = "RESTAURANT_LIST_FAILURE";
